trigger:
    branches:
        include:
            - master
            - develop
            - releases/*

jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    
    - task: FlutterBuild@0
      inputs:
        target: apk
        projectDirectory: '.'
