name: $(BuildID)

trigger:
    branches:
        include:
            - master
            - develop
            - releases/*
            
variables:
- group: MobileDeploymentVarGroup

jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    steps:
    - task: FlutterInstall@0
      inputs:
        channel: 'stable'
        version: 'latest'
    
    - task: FlutterBuild@0
      inputs:
        projectDirectory: '.'

    - task: AndroidSigning@3
      displayName: 'Signing and aligning APK file(s) **/*.apk'
      inputs:
        apkFiles: '**/*.apk'
        apksign: true
        apksignerKeystoreFile: upload-keystore.jks
        apksignerKeystorePassword: '$(AndroidKeyStorePassword)'
        apksignerKeystoreAlias: '$(AndroidKeyAlias)'
        apksignerKeyPassword: '$(AndroidKeyPassword)'
    
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
