name: $(BuildID)

trigger:
    branches:
        include:
            - master
            - develop
            - releases/*
            
variables:
- group: MobileDeploymentVarGroup

stages:
    - stage: 'Build'
      displayName: 'Build the Flutter App'
      jobs:
        - job: 'Android'
          displayName: 'Build Android'
          pool:
            vmImage: 'macOS-latest'
          steps:
          - task: FlutterInstall@0
            inputs:
              channel: 'stable'
              version: 'latest'
          
          - task: FlutterBuild@0
            inputs:
              projectDirectory: '.'

          - task: AndroidSigning@3
            displayName: 'Signing and aligning APK file(s) **/*.apk'
            inputs:
              apkFiles: '**/*.apk'
              apksign: true
              apksignerKeystoreFile: upload-keystore.jks
              apksignerKeystorePassword: '$(AndroidKeyStorePassword)'
              apksignerKeystoreAlias: '$(AndroidKeyAlias)'
              apksignerKeyPassword: '$(AndroidKeyPassword)'
          
          - task: CopyFiles@2
            inputs:
              contents: '**/*.apk'
              targetFolder: '$(build.artifactStagingDirectory)'

          - task: PublishBuildArtifacts@1

    - stage: 'Deploy'
      displayName: 'Deploy the Android App'
      dependsOn: Build
      condition: and (succeeded(), eq(variables['Build.SourceBranchName'], 'develop'))
      jobs:
          - deployment: Deploy
            pool:
              vmImage: 'macOS-latest'
            environment: Development
            strategy:
                runOnce:
                    deploy:
                        steps:
                            - download: current
                              artifact: drop
                            
                            - task: AppCenterDistribute@3
                              inputs:
                                serverEndpoint: 'app-center-micolk-android-conn'
                                appSlug: 'https://appcenter.ms/orgs/Mate.lk/apps/Mico.lk/'
                                appFile: '$(Pipeline.Workspace)/drop/build/outputs/apk/release/app-release.apk'
